purge recyclebin;

select * from user_tab_identity_cols;

no rows selected

select * from user_sequences where sequence_name like 'ISEQ$$%';

no rows selected;

DROP TABLE TB_DOCUMENT_TYPE;
DROP TABLE TB_CLIENT;
DROP TABLE TB_CAR;
DROP TABLE TB_INCIDENCE;
DROP TABLE TB_MECHANIC;
DROP TABLE TB_MECHANIC_SERVICE;
DROP TABLE TB_SERVICE;
DROP TABLE TB_BILL_SERVICE;
DROP TABLE TB_SITE;
DROP TABLE TB_REPLACEMENT;
DROP TABLE TB_REPLACEMENT_SITE;
DROP TABLE TB_BILL_REPLACEMENT_SITE;
DROP TABLE TB_BILL;